package billing_system;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.io.*;
import javax.swing.JOptionPane;

public class billing_systems extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(billing_systems.class.getName());

    private String getTime() {
        Date d = new Date();
        SimpleDateFormat timeFormatter = new SimpleDateFormat("hh:mm a");
        return timeFormatter.format(d);
    }

    private String getDate() {
        Date d = new Date();
        SimpleDateFormat dateFormatter = new SimpleDateFormat("dd-MMM-yyyy");
        return dateFormatter.format(d);
    }

    public billing_systems() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textTotal6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        textContact = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textNumber = new javax.swing.JTextField();
        updatebutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textPizzaitm = new javax.swing.JTextField();
        textPizzaunitP = new javax.swing.JTextField();
        textTotal1 = new javax.swing.JTextField();
        textBurgerunitP = new javax.swing.JTextField();
        textBurgeritm = new javax.swing.JTextField();
        textTotal2 = new javax.swing.JTextField();
        textFriesunitP = new javax.swing.JTextField();
        textFriesitm = new javax.swing.JTextField();
        textTotal3 = new javax.swing.JTextField();
        textSandwichunitP = new javax.swing.JTextField();
        textTotal4 = new javax.swing.JTextField();
        textSandwichitm = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        itxt2 = new javax.swing.JTextField();
        itxt1 = new javax.swing.JTextField();
        itxt3 = new javax.swing.JTextField();
        itxt4 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        textTotalP = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textDate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        textTime = new javax.swing.JTextField();
        buttonCalculate = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        jTextField7.setText("jTextField7");

        jLabel12.setText("jLabel12");

        textTotal6.setEditable(false);
        textTotal6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textTotal6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Billing System");
        setBackground(new java.awt.Color(204, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        textContact.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        textContact.setText("Contact Number : ");

        textName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Customer's Name :");

        textNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textNumber.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNumberKeyTyped(evt);
            }
        });

        updatebutton.setFont(new java.awt.Font("Times New Roman", 3, 10)); // NOI18N
        updatebutton.setText("Admin Panel");
        updatebutton.addActionListener(this::updatebuttonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updatebutton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updatebutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textContact)
                    .addComponent(textNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fast-Food Billing System");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Items");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Item Oty");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Unit Price");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Total Price");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Pizza:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Burger:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Sandwich:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Fries:");

        textPizzaitm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textPizzaitm.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textPizzaitm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPizzaitmKeyTyped(evt);
            }
        });

        textPizzaunitP.setEditable(false);
        textPizzaunitP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textPizzaunitP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textPizzaunitP.setText("0.00");
        

        textTotal1.setEditable(false);
        textTotal1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textTotal1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        textBurgerunitP.setEditable(false);
        textBurgerunitP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textBurgerunitP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textBurgerunitP.setText("0.00");

        textBurgeritm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textBurgeritm.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textBurgeritm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textBurgeritmKeyTyped(evt);
            }
        });

        textTotal2.setEditable(false);
        textTotal2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textTotal2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        textFriesunitP.setEditable(false);
        textFriesunitP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textFriesunitP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFriesunitP.setText("0.00");

        textFriesitm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textFriesitm.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textFriesitm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFriesitmKeyTyped(evt);
            }
        });

        textTotal3.setEditable(false);
        textTotal3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textTotal3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        textSandwichunitP.setEditable(false);
        textSandwichunitP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textSandwichunitP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textSandwichunitP.setText("0.00");

        textTotal4.setEditable(false);
        textTotal4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textTotal4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        textSandwichitm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textSandwichitm.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textSandwichitm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textSandwichitmKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Item Left");

        itxt2.setEditable(false);
        itxt2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        itxt2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        itxt1.setEditable(false);
        itxt1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        itxt1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        itxt3.setEditable(false);
        itxt3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        itxt3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        itxt4.setEditable(false);
        itxt4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        itxt4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textBurgeritm, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(textFriesitm, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addComponent(textPizzaitm, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(25, 25, 25)
                        .addComponent(textSandwichitm, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5)))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textBurgerunitP, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPizzaunitP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFriesunitP, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSandwichunitP, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTotal4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itxt3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(itxt2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itxt1)
                    .addComponent(itxt4))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itxt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(textPizzaitm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textPizzaunitP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(textBurgeritm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textBurgerunitP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFriesunitP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFriesitm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(itxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSandwichunitP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTotal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSandwichitm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(itxt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Total Price: ");

        textTotalP.setEditable(false);
        textTotalP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        textTotalP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Date:");

        textDate.setEditable(false);
        textDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textDate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Time:");

        textTime.setEditable(false);
        textTime.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textTime.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        buttonCalculate.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buttonCalculate.setText("Calculate");
        buttonCalculate.addActionListener(this::buttonCalculateActionPerformed);

        buttonSave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buttonSave.setText("Save");
        buttonSave.addActionListener(this::buttonSaveActionPerformed);

        buttonExit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buttonExit.setText("Reset");
        buttonExit.addActionListener(this::buttonExitActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(textTotalP, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(buttonCalculate)
                        .addGap(30, 30, 30)
                        .addComponent(buttonSave)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textTime, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDate, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(textTotalP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCalculate)
                    .addComponent(buttonSave)
                    .addComponent(buttonExit))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {

        double pizza = Double.parseDouble(textPizzaunitP.getText());
        double burger = Double.parseDouble(textBurgerunitP.getText());
        double fries = Double.parseDouble(textFriesunitP.getText());
        double sandwich = Double.parseDouble(textSandwichunitP.getText());

        String name = textName.getText().trim();
        String contact = textContact.getText().trim();

        if (name.isEmpty() || contact.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter name and contact");
            return;
        }

        name = name.replace(",", " ");
        contact = contact.replace(",", " ");

        double pizza_qty = textPizzaitm.getText().isBlank() ? 0 : Double.parseDouble(textPizzaitm.getText());
        double burger_qty = textBurgeritm.getText().isBlank() ? 0 : Double.parseDouble(textBurgeritm.getText());
        double fries_qty = textFriesitm.getText().isBlank() ? 0 : Double.parseDouble(textFriesitm.getText());
        double sandwich_qty = textSandwichitm.getText().isBlank() ? 0 : Double.parseDouble(textSandwichitm.getText());
        
        double currentPizzaStock = itxt1.getText().isBlank() ? 0 : Double.parseDouble(itxt1.getText());
        double currentBurgerStock = itxt2.getText().isBlank() ? 0 : Double.parseDouble(itxt2.getText());
        double currentFriesStock = itxt3.getText().isBlank() ? 0 : Double.parseDouble(itxt3.getText());
        double currentSandwichStock = itxt4.getText().isBlank() ? 0 : Double.parseDouble(itxt4.getText());

        if (pizza_qty > currentPizzaStock || burger_qty > currentBurgerStock
                || fries_qty > currentFriesStock || sandwich_qty > currentSandwichStock) {
            javax.swing.JOptionPane.showMessageDialog(this, "Not enough stock available!", "Stock Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        double total_price = (pizza_qty * pizza) + (burger_qty * burger) + (fries_qty * fries) + (sandwich_qty * sandwich);
        System.out.println("Total Price: " + total_price);
        String dateStr = getDate();
        String timeStr = getTime();

        /*ADD your Folder Path here including file name and the file should be .csv*/

        File csvFile = new File("D:\\DOCUMENT\\Java\\billing_system\\restaurant_billing.csv");
        boolean isNewFile = !csvFile.exists();

        try (FileWriter fw = new FileWriter(csvFile, true); BufferedWriter writer = new BufferedWriter(fw)) {

            if (isNewFile) {
                writer.write("Name, Contact Number, Pizza, Burger, Fries, Sandwich, Total Price, Date, Time");
                writer.newLine();
            }

            String csvRow = String.format("%s, %s, %.2f, %.2f, %.2f, %.2f, %.2f, %s, %s",
                    name, contact, pizza_qty, burger_qty, fries_qty, sandwich_qty, total_price, dateStr, timeStr);

            writer.write(csvRow);
            writer.newLine();
            writer.flush();

            int newPizzaStock = (int) (currentPizzaStock - pizza_qty);
            int newBurgerStock = (int) (currentBurgerStock - burger_qty);
            int newFriesStock = (int) (currentFriesStock - fries_qty);
            int newSandwichStock = (int) (currentSandwichStock - sandwich_qty);

            itxt1.setText(String.valueOf(newPizzaStock));
            itxt2.setText(String.valueOf(newBurgerStock));
            itxt3.setText(String.valueOf(newFriesStock));
            itxt4.setText(String.valueOf(newSandwichStock));
            
            JOptionPane.showMessageDialog(this, "Customer's data saved successfully!");

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "There is an Error: " + e.getMessage());
        }
        
    }

    private void textPizzaitmKeyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }

    private void textBurgeritmKeyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }

    private void textFriesitmKeyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }

    private void textSandwichitmKeyTyped(java.awt.event.KeyEvent evt) {
        
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }

    private void textNumberKeyTyped(java.awt.event.KeyEvent evt) { 
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    } 

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) { 

        textName.setText(null);
        textNumber.setText(null);
        textPizzaitm.setText(null);
        textBurgeritm.setText(null);
        textFriesitm.setText(null);
        textSandwichitm.setText(null);
        textTotal1.setText(null);
        textTotal2.setText(null);
        textTotal3.setText(null);
        textTotal4.setText(null);
        textTotalP.setText(null);
        textDate.setText(null);
        textTime.setText(null);
    } 

    private void buttonCalculateActionPerformed(java.awt.event.ActionEvent evt) { 

        double pizza = Double.parseDouble(textPizzaunitP.getText());
        double burger = Double.parseDouble(textBurgerunitP.getText());
        double fries = Double.parseDouble(textFriesunitP.getText());
        double sandwich = Double.parseDouble(textSandwichunitP.getText());

        textDate.setText(getDate());
        textTime.setText(getTime());

        double pizza_qty = textPizzaitm.getText().isBlank() ? 0 : Double.parseDouble(textPizzaitm.getText());
        double burger_qty = textBurgeritm.getText().isBlank() ? 0 : Double.parseDouble(textBurgeritm.getText());
        double fries_qty = textFriesitm.getText().isBlank() ? 0 : Double.parseDouble(textFriesitm.getText());
        double sandwich_qty = textSandwichitm.getText().isBlank() ? 0 : Double.parseDouble(textSandwichitm.getText());

        if (pizza_qty == 0) {
            textPizzaitm.setText("" + 0);
        }
        if (burger_qty == 0) {
            textBurgeritm.setText("" + 0);
        }
        if (fries_qty == 0) {
            textFriesitm.setText("" + 0);
        }
        if (sandwich_qty == 0) {
            textSandwichitm.setText("" + 0);
        }

        double totalpizza = pizza_qty * pizza;
        double totalburger = burger_qty * burger;
        double totalfries = fries_qty * fries;
        double totalsandwich = sandwich_qty * sandwich;

        textTotal1.setText(String.valueOf(totalpizza));
        textTotal2.setText(String.valueOf(totalburger));
        textTotal3.setText(String.valueOf(totalfries));
        textTotal4.setText(String.valueOf(totalsandwich));

        double total_price = totalpizza + totalburger + totalfries + totalsandwich;
        textTotalP.setText(String.valueOf(total_price));

    } 

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JPasswordField pf = new javax.swing.JPasswordField();
        int passOption = javax.swing.JOptionPane.showConfirmDialog(
                this,
                pf,
                "Enter Admin Password:",
                javax.swing.JOptionPane.OK_CANCEL_OPTION,
                javax.swing.JOptionPane.PLAIN_MESSAGE
        );
        if (passOption == javax.swing.JOptionPane.OK_OPTION) {
            String inputPassword = new String(pf.getPassword());
            String adminPassword = "1234";
            if (inputPassword.equals(adminPassword)) {

                String[] options = {"Update Price", "Update Stock Quantity"};
                int choice = javax.swing.JOptionPane.showOptionDialog(
                        this,
                        "What would you like to update?",
                        "Admin Panel Options",
                        javax.swing.JOptionPane.DEFAULT_OPTION,
                        javax.swing.JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        options[0]
                );
                if (choice == 0) {
                    NewJDialog dialog = new NewJDialog(this, true);
                    dialog.setLocationRelativeTo(this);
                    dialog.setVisible(true);
                    
                  

                    if (dialog.isUpdated) {
                        textPizzaunitP.setText(dialog.getPizzaPrice());
                        textBurgerunitP.setText(dialog.getBurgerPrice());
                        textFriesunitP.setText(dialog.getFriesPrice());
                        textSandwichunitP.setText(dialog.getSandwichPrice());

                        javax.swing.JOptionPane.showMessageDialog(this, "Unit Prices Updated Successfully!");
                    }
                } else if (choice == 1) {
                    stockqty stockDialog = new stockqty(this, true);
                    stockDialog.setLocationRelativeTo(this);
                    stockDialog.setVisible(true);

                    if (stockDialog.isStockUpdated) {
                        itxt1.setText(stockDialog.getPizzaStock());
                        itxt2.setText(stockDialog.getBurgerStock());
                        itxt3.setText(stockDialog.getFriesStock());
                        itxt4.setText(stockDialog.getSandwichStock());

                        javax.swing.JOptionPane.showMessageDialog(this, "Stock Quantity Updated Successfully!");
                    }
                }
            } else if (inputPassword != null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Incorrect Password!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> new billing_systems().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalculate;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonSave;
    private javax.swing.JTextField itxt1;
    private javax.swing.JTextField itxt2;
    private javax.swing.JTextField itxt3;
    private javax.swing.JTextField itxt4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField textBurgeritm;
    private javax.swing.JTextField textBurgerunitP;
    private javax.swing.JLabel textContact;
    private javax.swing.JTextField textDate;
    private javax.swing.JTextField textFriesitm;
    private javax.swing.JTextField textFriesunitP;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textNumber;
    private javax.swing.JTextField textPizzaitm;
    private javax.swing.JTextField textPizzaunitP;
    private javax.swing.JTextField textSandwichitm;
    private javax.swing.JTextField textSandwichunitP;
    private javax.swing.JTextField textTime;
    private javax.swing.JTextField textTotal1;
    private javax.swing.JTextField textTotal2;
    private javax.swing.JTextField textTotal3;
    private javax.swing.JTextField textTotal4;
    private javax.swing.JTextField textTotal6;
    private javax.swing.JTextField textTotalP;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables
}
